### PR TITLE
lxcCompat1

### PR DESCRIPTION
**Pull request by gamerson**
- read LCP.json kind to determine Job vs Deployment workload
- bump versions

### CODE REVIEW

**Comment by gamerson** [comment]
hey @allen-ziegenfus if you have blocks like this:
```
runtime:
    type: configuration
    workload: job
```

This is not read anymore for `next`. now we ready the `LCP.json` directly.  So let me know if you see any issues here.

**Comment by allen-ziegenfus** [comment]
@gamerson  so that means we always have to commit a LCP.json? Are you sure brian is on board with that?

**Comment by rotty3000** [comment]
@gamerson could we instead read the LCP.json in the `build` directory? That way we use the auto-provided one if there isn't one committed in the project.

I realize that that might force you to ensure a build occurred before being able to generate the workload configuration.

**Comment by rotty3000** [comment]
we could move the logic for resource calculation into the `process_extension` function after `custom_build` since none of the parameters are used until after that anyway.

**Comment by gamerson** [comment]
> @gamerson so that means we always have to commit a LCP.json? Are you sure brian is on board with that?

No I'm not sure on this part yet.

**Comment by gamerson** [comment]
> we could move the logic for resource calculation into the `process_extension` function after `custom_build` since none of the parameters are used until after that anyway.

Agreed, I can make that change.

**Comment by gamerson** [comment]
Hey @rotty3000  i had to back out the change to readling LCP.json from the build/ directory, it was causing some weird effects that we need to dig in a little.

**Pull request merged**
