### PR TITLE
this _should_ fix the mysql test

### PR DESCRIPTION
**Pull request by rotty3000**
- remove old image reference
- refactor Tilefile.* so they can be used together without merging
- add missing template arguments
- less sleep for better responsiveness
- just copy the file
- verbose output so we don't have to dump logs
- remove extra argument
- SF

### CODE REVIEW

**Comment by gamerson** [comment]
wow! green builds!

**Review by gamerson — APPROVED** [review]
LGTM!

**Comment by rotty3000** [comment]
strange that it's the only test that failed this time :|

**Comment by rotty3000** [comment]
... oh, but I see why!

**Pull request merged**
